# Disable blank line between shell prompts
add_newline = false

# Disable prompting in two lines
[line_break]
disabled = true

# Set ending char to "$"
[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

# Show hostname
[hostname]
ssh_only = false
format = "[$hostname \\]](bold red) "

# Show username 
[username]
show_always = true
format = "[\\[ $user](bold yellow)@"

# Remove nodejs
[nodejs]
disabled = true
